const EPSILON=1e-7;
export const AIM_PROFILES=Object.freeze({relaxed:Object.freeze({assistance:1,ghost:true}),normal:Object.freeze({assistance:.62,ghost:true}),hard:Object.freeze({assistance:.34,ghost:false}),adaptive:Object.freeze({assistance:.58,ghost:true})});
const pointAt=(o,d,v)=>({x:o.x+d.x*v,y:o.y+d.y*v});
const TYPE_ORDER={BALL:0,POCKET_JAW:1,POCKET_THROAT:2,CUSHION:3,BUMPER:4,ECHO_RAIL:5};
export function rayExpandedCircle(o,d,c,r=0){const x=o.x-c.x,y=o.y-c.y,R=c.r+r,b=x*d.x+y*d.y,q=b*b-(x*x+y*y-R*R);if(q<0)return null;const distance=-b-Math.sqrt(Math.max(0,q));if(distance<=EPSILON)return null;const cueCenter=pointAt(o,d,distance),nx=(cueCenter.x-c.x)/R,ny=(cueCenter.y-c.y)/R;return{distance,cueCenter,point:{x:c.x+nx*c.r,y:c.y+ny*c.r},normal:{x:nx,y:ny}}}
export function rayCapsule(o,d,s,r=0){const sx=s.b.x-s.a.x,sy=s.b.y-s.a.y,L=Math.hypot(sx,sy);if(L<EPSILON)return rayExpandedCircle(o,d,{x:s.a.x,y:s.a.y,r:s.radius||0},r);const tx=sx/L,ty=sy/L,nx=-ty,ny=tx,px=o.x-s.a.x,py=o.y-s.a.y,along=px*tx+py*ty,forward=d.x*tx+d.y*ty,across=px*nx+py*ny,nv=d.x*nx+d.y*ny,R=(s.radius||0)+r;let best=null;if(Math.abs(nv)>EPSILON)for(const side of [-1,1]){const distance=(side*R-across)/nv,projection=along+forward*distance;if(distance>EPSILON&&projection>=-EPSILON&&projection<=L+EPSILON){const cueCenter=pointAt(o,d,distance),normal={x:nx*side,y:ny*side};best={distance,cueCenter,point:{x:cueCenter.x-normal.x*r,y:cueCenter.y-normal.y*r},normal};break}}for(const endpoint of [s.a,s.b]){const hit=rayExpandedCircle(o,d,{x:endpoint.x,y:endpoint.y,r:s.radius||0},r);if(hit&&(!best||hit.distance<best.distance))best=hit}return best}
export function rayBounds(o,d,b,r=0){const hits=[];if(d.x>EPSILON)hits.push({distance:(b.r-r-o.x)/d.x,normal:{x:-1,y:0},part:'right'});if(d.x<-EPSILON)hits.push({distance:(b.l+r-o.x)/d.x,normal:{x:1,y:0},part:'left'});if(d.y>EPSILON)hits.push({distance:(b.b-r-o.y)/d.y,normal:{x:0,y:-1},part:'bottom'});if(d.y<-EPSILON)hits.push({distance:(b.t+r-o.y)/d.y,normal:{x:0,y:1},part:'top'});const hit=hits.filter(x=>x.distance>EPSILON).sort((a,b)=>a.distance-b.distance||a.part.localeCompare(b.part))[0];return hit&&{...hit,cueCenter:pointAt(o,d,hit.distance),point:pointAt(o,d,hit.distance)}}
function choose(hits){return hits.filter(Boolean).sort((a,b)=>a.distance-b.distance||TYPE_ORDER[a.type]-TYPE_ORDER[b.type]||String(a.id).localeCompare(String(b.id)))[0]||null}
export function deriveAimPreview({table,cueBall,shotDirection,shotSpeed=0,assistance=1,maxPhysicalTravel=0,trace=false}){const o={x:cueBall.x,y:cueBall.y},raw=shotDirection||{x:0,y:0},m=Math.hypot(raw.x,raw.y),physicalReach=Math.max(0,maxPhysicalTravel),assistanceReach=physicalReach*Math.max(0,assistance)*(trace?1.8:1),limit=Math.min(physicalReach,assistanceReach);if(m<EPSILON||shotSpeed<=0||limit<=EPSILON)return{physicalReach,assistanceReach,displayedDistance:0,reachableDistance:physicalReach,firstHit:null,ghostCue:null,segments:[]};const d={x:raw.x/m,y:raw.y/m},hits=[];for(const ball of table.balls||[])if(ball!==cueBall&&!ball.pocketed){const hit=rayExpandedCircle(o,d,ball,cueBall.r);if(hit)hits.push({...hit,type:'BALL',id:ball.id,part:'ball'})}for(const [i,b] of (table.obstacles||[]).entries()){const hit=rayExpandedCircle(o,d,b,cueBall.r);if(hit)hits.push({...hit,type:'BUMPER',id:i,part:'bumper'})}for(const [i,rail] of (table.rails||[]).entries()){const hit=rayCapsule(o,d,{...rail,radius:rail.radius??5},cueBall.r);if(hit)hits.push({...hit,type:'ECHO_RAIL',id:i,part:'echo-rail'})}if(table.pocketModel==='physical')for(const [i,s] of (table.pocketGeometry?.segments||[]).entries()){const hit=rayCapsule(o,d,s,cueBall.r);if(hit)hits.push({...hit,type:s.part==='jaw'?'POCKET_JAW':s.part==='throat'||s.part==='back'?'POCKET_THROAT':'CUSHION',id:s.contactId||i,part:s.part,pocketId:s.pocketId})}else{const hit=rayBounds(o,d,table.bounds,cueBall.r);if(hit)hits.push({...hit,type:'CUSHION',id:hit.part,part:hit.part})}const firstHit=choose(hits.filter(h=>h.distance<=limit+EPSILON)),distance=firstHit?firstHit.distance:limit,to=pointAt(o,d,distance);return{physicalReach,assistanceReach,displayedDistance:distance,reachableDistance:physicalReach,firstHit,ghostCue:firstHit?.type==='BALL'?{x:firstHit.cueCenter.x,y:firstHit.cueCenter.y,r:cueBall.r,contact:firstHit.point}:null,segments:distance?[{from:o,to,type:firstHit?.type||'REACH'}]:[]}}
