import {clamp,len,hashString} from './math.js';import {generateTable,dailySeed,DIFFICULTY} from './generator.js';import {Physics,STEP,echoFromPath} from './physics.js';import {loadSave,save,exportSave,importSave} from './storage.js';import {AudioFX} from './audio.js';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d',{alpha:false});let data=loadSave(),game=null,acc=0,last=performance.now(),drag=null,particles=[],toastTimer,paused=false;const audio=new AudioFX();
const MODE_INFO={flow:'3 falhas — mantém a série',zen:'Sem pressão — joga livremente',precision:'2 jogadas — segue a condição',rush:'45 segundos — sucessos dão +5s',daily:'A mesma seed para todos hoje'};
class Game{
 constructor(){this.mode=data.mode;this.difficulty=data.difficulty;this.score=0;this.streak=0;this.level=0;this.failures=0;this.remaining=45;this.shotsLeft=2;this.seedBase=this.mode==='daily'?dailySeed():Date.now()>>>0;this.next()}
 adaptive(){const r=data.stats.recent||[],rate=r.length?r.filter(Boolean).length/r.length:.5;return rate>.7?2:rate<.35?-1:0}
 next(){const echoes=(this.table?.rails||[]).map(r=>({...r,life:r.life-1})).filter(r=>r.life>0);const seed=(this.seedBase+Math.imul(this.level+1,2654435761))>>>0;this.table=generateTable(seed,this.difficulty,this.adaptive());this.table.rails=echoes;this.physics=new Physics(this.table);this.shotsLeft=this.mode==='precision'?2:99;this.condition=this.mode==='precision'?(this.level%2?'ORDEM: rosa → dourada':'MÍNIMO 2 RESSALTOS'):'';this.level++;updateHUD()}
 shoot(vx,vy){if(this.physics.active)return;this.physics.shoot(vx,vy);data.stats.shots++;if(this.mode==='precision')this.shotsLeft--;save(data)}
 finish(){let ok=this.physics.contacts.size===2;if(this.mode==='precision')ok=ok&&(this.level%2===0?this.physics.contactOrder[0]===2:this.physics.cushions>=2);record(ok);if(ok){this.streak++;const mult=1+Math.min(4,Math.floor(this.streak/3));const bonus=100*mult+this.physics.cushions*15;this.score+=bonus;if(this.mode==='rush')this.remaining=Math.min(60,this.remaining+5);const rail=echoFromPath(this.physics.path);if(rail){this.table.rails.push(rail);const max=DIFFICULTY[this.difficulty].rails;while(this.table.rails.length>max)this.table.rails.shift()}audio.success();buzz([18,35,18]);burst(this.table.balls[0].x,this.table.balls[0].y,'#5cf3dc');showToast(`ECHO +${bonus}`);unlock();setTimeout(()=>this.next(),850)}else{this.streak=0;this.failures++;audio.fail();buzz(30);showToast(this.physics.contacts.size?`QUASE · ${this.physics.contacts.size}/2`:'SEM ECO');if(this.mode==='zen'||this.difficulty==='relaxed'){setTimeout(()=>this.resetPositions(),800)}else if(this.mode==='precision'&&this.shotsLeft>0){setTimeout(()=>this.resetPositions(),800)}else if((this.mode==='flow'||this.mode==='daily')&&this.failures<DIFFICULTY[this.difficulty].lives){setTimeout(()=>this.next(),800)}else setTimeout(()=>endGame(),900)}updateHUD()}
 resetPositions(){for(const b of this.table.balls){b.vx=b.vy=0}this.physics.active=false;updateHUD()}
}
function record(ok){data.stats.successes+=ok?1:0;data.stats.recent=[...(data.stats.recent||[]),ok].slice(-12);if(game.mode==='daily'&&ok){const d=new Date().toISOString().slice(0,10);if(!data.dailies.includes(d))data.dailies.push(d)}save(data)}
function unlock(){if(game.streak>=3)addAchievement('Primeiro Eco','Consegue 3 carambolas seguidas');if(game.physics.cushions>=4)addAchievement('Arquitecto','Usa 4 ressaltos numa carambola');if(data.stats.successes>=25)addAchievement('Ressonância','Completa 25 carambolas')}
function addAchievement(id,desc){if(data.achievements.some(a=>a.id===id))return;data.achievements.push({id,desc,date:new Date().toISOString()});save(data);showToast(`CONQUISTA · ${id}`)}
function resize(){const r=$('#stage').getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
function map(e){const r=canvas.getBoundingClientRect(),t=game.table;return{x:(e.clientX-r.left)/r.width*t.w,y:(e.clientY-r.top)/r.height*t.h}}
function down(e){if(!game||game.physics.active||paused)return;audio.unlock();const p=map(e),b=game.table.balls[0];if(Math.hypot(p.x-b.x,p.y-b.y)<95){drag={start:{x:b.x,y:b.y},p,id:e.pointerId};canvas.setPointerCapture(e.pointerId);if(!data.tutorial)coach(1)}}
function move(e){if(drag&&e.pointerId===drag.id){drag.p=map(e);if(!data.tutorial)coach(2)}}
function up(e){if(!drag||e.pointerId!==drag.id)return;const dx=drag.start.x-drag.p.x,dy=drag.start.y-drag.p.y,d=Math.hypot(dx,dy);drag=null;if(d<24)return;const max=DIFFICULTY[game.difficulty].power,s=Math.min(max,d*4.2);game.shoot(dx/d*s,dy/d*s);audio.hit(s/max);if(!data.tutorial){coach(3);data.tutorial=true;save(data);setTimeout(()=>$('#tutorial').classList.add('hidden'),2400)}}
function coach(n){const titles=['','ARRASTA','LARGA','TOCA NAS DUAS'];const text=['','Puxa a partir da bola branca para apontar','A distância controla a força','Qualquer ordem completa a carambola'];$('#coachTitle').textContent=titles[n];$('#coachText').textContent=text[n];$('#tutorial').classList.remove('hidden')}
function update(dt){if(paused||!game)return;if(game.mode==='rush'){game.remaining-=dt;$('#status').textContent=Math.max(0,Math.ceil(game.remaining));if(game.remaining<=0){game.remaining=0;endGame();return}}if(game.physics.active){acc+=dt;let n=0;while(acc>=STEP&&n++<16){if(game.physics.step(STEP)){game.finish();acc=0;break}acc-=STEP}}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}
function render(){if(!game)return;const W=canvas.clientWidth,H=canvas.clientHeight,sx=W/game.table.w,sy=H/game.table.h;ctx.setTransform((devicePixelRatio>2?2:devicePixelRatio||1)*sx,0,0,(devicePixelRatio>2?2:devicePixelRatio||1)*sy,0,0);const t=game.table;ctx.fillStyle='#071a21';ctx.fillRect(0,0,t.w,t.h);ctx.strokeStyle='#23434a';ctx.lineWidth=3;ctx.strokeRect(t.bounds.l,t.bounds.t,t.bounds.r-t.bounds.l,t.bounds.b-t.bounds.t);ctx.globalAlpha=.12;ctx.strokeStyle='#5cf3dc';ctx.lineWidth=1;for(let y=120;y<t.h;y+=120){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(t.w,y);ctx.stroke()}ctx.globalAlpha=1;
 if(t.frictionZone){ctx.fillStyle=t.frictionZone.factor>1?'#ffca6815':'#5cf3dc12';ctx.strokeStyle=t.frictionZone.factor>1?'#ffca6860':'#5cf3dc60';roundRect(t.frictionZone.x,t.frictionZone.y,t.frictionZone.w,t.frictionZone.h,18,true,true);ctx.fillStyle='#9ab1b3';ctx.font='18px system-ui';ctx.fillText(t.frictionZone.factor>1?'SLOW':'GLIDE',t.frictionZone.x+12,t.frictionZone.y+27)}
 for(const r of t.rails){ctx.strokeStyle='#5cf3dc88';ctx.shadowColor='#5cf3dc';ctx.shadowBlur=14;ctx.lineWidth=10;ctx.beginPath();ctx.moveTo(r.a.x,r.a.y);ctx.lineTo(r.b.x,r.b.y);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#cafff0aa';ctx.lineWidth=2;ctx.stroke()}
 for(const o of t.obstacles){ctx.fillStyle='#172e37';ctx.strokeStyle='#ffca68';ctx.lineWidth=4;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,7);ctx.fill();ctx.stroke()}
 if(drag){const b=t.balls[0],dx=b.x-drag.p.x,dy=b.y-drag.p.y,d=Math.hypot(dx,dy)||1,pow=clamp(d/180,0,1),preview=DIFFICULTY[game.difficulty].preview;ctx.setLineDash([12,10]);ctx.strokeStyle='#efffffaa';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x+dx/d*330*preview,b.y+dy/d*330*preview);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#5cf3dc';ctx.lineWidth=7;ctx.beginPath();ctx.arc(b.x,b.y,b.r+14,-Math.PI/2,-Math.PI/2+Math.PI*2*pow);ctx.stroke()}
 const colors=['#ecffff','#ffca68','#ff6d9e'];for(const b of t.balls){ctx.shadowColor=colors[b.id];ctx.shadowBlur=18;const g=ctx.createRadialGradient(b.x-6,b.y-8,2,b.x,b.y,b.r);g.addColorStop(0,'#fff');g.addColorStop(.22,colors[b.id]);g.addColorStop(1,'#16303a');ctx.fillStyle=g;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill();ctx.shadowBlur=0;if(b.id){ctx.fillStyle='#071a21';ctx.font='bold 14px system-ui';ctx.textAlign='center';ctx.fillText(String(b.id),b.x,b.y+5);ctx.textAlign='left'}}
 for(const p of particles){ctx.globalAlpha=p.life;ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,5,5)}ctx.globalAlpha=1}
function roundRect(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill)ctx.fill();if(stroke)ctx.stroke()}
function burst(x,y,c){if(data.settings.reducedMotion)return;for(let i=0;i<22;i++){const a=Math.random()*7,s=50+Math.random()*140;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.5+Math.random()*.4,c})}}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;update(dt);render();requestAnimationFrame(loop)}
function buzz(p){if(data.settings.haptics&&navigator.vibrate)navigator.vibrate(p)}
function showToast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),900)}
function updateHUD(){if(!game)return;$('#score').textContent=game.score;$('#streak').textContent=game.streak;let label='VIDAS',value='●'.repeat(Math.max(0,DIFFICULTY[game.difficulty].lives-game.failures));if(game.mode==='zen'){label='NÍVEL';value=game.level}if(game.mode==='precision'){label='JOGADAS';value=game.shotsLeft}if(game.mode==='rush'){label='TEMPO';value=Math.ceil(game.remaining)}$('#statusLabel').textContent=label;$('#status').textContent=value;$('#objective').textContent=game.condition||MODE_INFO[game.mode]}
function start(){data.mode=$('#mode').value;data.difficulty=$('#difficulty').value;save(data);game=new Game();$('#menu').close();paused=false;if(!data.tutorial)coach(1)}
function endGame(){if(!game)return;const m=game.mode;data.best[m]=Math.max(data.best[m]||0,game.score);data.bestStreak=Math.max(data.bestStreak,game.streak);save(data);showToast(`FIM · ${game.score}`);setTimeout(()=>{$('#menu').showModal();paused=true},700)}
function openSettings(){paused=true;audio.enabled=data.settings.sound;$('#sound').checked=data.settings.sound;$('#haptics').checked=data.settings.haptics;$('#reduced').checked=data.settings.reducedMotion;$('#settings').showModal()}
canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>drag=null);window.addEventListener('resize',resize);$('#playBtn').onclick=start;$('#settingsBtn').onclick=openSettings;$('#openSettings').onclick=openSettings;$('#homeBtn').onclick=()=>{paused=true;$('#menu').showModal()};$('#retryBtn').onclick=()=>game&&!game.physics.active&&game.next();
for(const b of document.querySelectorAll('dialog .close'))b.onclick=()=>{b.closest('dialog').close();paused=$('#menu').open};$('#mode').value=data.mode;$('#difficulty').value=data.difficulty;$('#progressBtn').onclick=()=>{const a=data.achievements.map(x=>`✓ ${x.id}`).join('<br>')||'Ainda sem conquistas';$('#stats').innerHTML=`Jogadas: ${data.stats.shots}<br>Carambolas: ${data.stats.successes}<br>Melhor série: ${data.bestStreak}<hr>${a}`;$('#progress').showModal()};
$('#tutorialBtn').onclick=()=>{data.tutorial=false;save(data);$('#settings').close();paused=false;coach(1)};$('#sound').onchange=e=>{data.settings.sound=e.target.checked;audio.enabled=e.target.checked;save(data)};$('#haptics').onchange=e=>{data.settings.haptics=e.target.checked;save(data)};$('#reduced').onchange=e=>{data.settings.reducedMotion=e.target.checked;save(data)};$('#exportBtn').onclick=()=>{const u=URL.createObjectURL(exportSave(data)),a=document.createElement('a');a.href=u;a.download='tri-echo-progress.json';a.click();URL.revokeObjectURL(u)};$('#importFile').onchange=async e=>{try{data=await importSave(e.target.files[0]);save(data);showToast('PROGRESSO IMPORTADO')}catch{showToast('FICHEIRO INVÁLIDO')}};
window.__TRI_ECHO__={state:()=>game&&({active:game.physics.active,score:game.score,cue:{x:game.table.balls[0].x/game.table.w,y:game.table.balls[0].y/game.table.h},contacts:game.physics.contacts.size,rails:game.table.rails.length})};document.addEventListener('visibilitychange',()=>paused=document.hidden||$('#menu').open||$('#settings').open||$('#progress').open);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));resize();$('#menu').showModal();paused=true;requestAnimationFrame(loop);
