import test from 'node:test';
import assert from 'node:assert/strict';
import {createPocketGeometry} from '../js/pocket-geometry.js';
import {deriveAimPreview} from '../js/aim-preview.js';
import {estimateStoppingDistance,simulateStoppingDistance} from '../js/physics-calibration.js';

const ball=(id,x,y,r=18)=>({id,x,y,r,pocketed:false});
const plain=()=>({bounds:{l:0,r:600,t:0,b:400},balls:[ball(0,80,200),ball(1,260,200)],obstacles:[],rails:[],pocketModel:'none'});
const aim=(table,extra={})=>deriveAimPreview({table,cueBall:table.balls[0],shotDirection:{x:1,y:0},shotSpeed:900,assistance:1,maxPhysicalTravel:1000,...extra});

test('nearest_ball_hit and ghost contact are exact',()=>{const table=plain(),preview=aim(table);assert.equal(preview.firstHit.type,'BALL');assert.equal(preview.firstHit.id,1);assert.ok(Math.abs(Math.hypot(preview.ghostCue.x-table.balls[1].x,preview.ghostCue.y-table.balls[1].y)-(18+18))<1e-6);assert.ok(Math.abs(preview.ghostCue.contact.x-(table.balls[1].x-18))<1e-6)});
test('thin cut and mixed radii preserve ghost-contact precision',()=>{const table=plain();table.balls[1]={...table.balls[1],y:228,r:15};const preview=aim(table);assert.equal(preview.firstHit.type,'BALL');const target=table.balls[1],ghost=preview.ghostCue,contact=ghost.contact;assert.ok(Math.abs(Math.hypot(ghost.x-target.x,ghost.y-target.y)-(18+15))<1e-6);assert.ok(Math.abs((contact.x-ghost.x)*(target.y-ghost.y)-(contact.y-ghost.y)*(target.x-ghost.x))<1e-5)});
test('wall, bumper and echo rail are first physical interactions',()=>{const table=plain();table.balls.splice(1);assert.equal(aim(table).firstHit.type,'CUSHION');table.obstacles=[{x:180,y:200,r:24}];assert.equal(aim(table).firstHit.type,'BUMPER');table.obstacles=[];table.rails=[{a:{x:160,y:160},b:{x:160,y:240}}];assert.equal(aim(table).firstHit.type,'ECHO_RAIL')});
test('physical mouth is not treated as a closed rectangular wall and jaws are',()=>{const bounds={l:40,r:560,t:40,b:360},geometry=createPocketGeometry(bounds,36,'american'),table={bounds,balls:[ball(0,300,200)],obstacles:[],rails:[],pocketModel:'physical',pocketGeometry:geometry};const side=geometry.pockets.find(p=>p.type==='side'&&p.mouth.x===bounds.r);let preview=deriveAimPreview({table,cueBall:table.balls[0],shotDirection:{x:1,y:0},shotSpeed:900,assistance:1,maxPhysicalTravel:1000});assert.equal(preview.firstHit.type,'POCKET_THROAT');assert.notEqual(preview.firstHit.type,'CUSHION');table.balls[0].y=side.mouth.y+side.width*.55;preview=deriveAimPreview({table,cueBall:table.balls[0],shotDirection:{x:1,y:0},shotSpeed:900,assistance:1,maxPhysicalTravel:1000});assert.equal(preview.firstHit.type,'POCKET_JAW')});
test('nearest hit has stable deterministic tie-breaking',()=>{const table=plain();table.balls.push(ball(2,260,200));const values=Array.from({length:10},()=>aim(table).firstHit.id);assert.deepEqual(values,Array(10).fill(1))});
test('zero power has zero reach and reach grows with power',()=>{const table=plain(),zero=deriveAimPreview({table,cueBall:table.balls[0],shotDirection:{x:1,y:0},shotSpeed:0,assistance:1,maxPhysicalTravel:0}),a=estimateStoppingDistance(400),b=estimateStoppingDistance(900);assert.equal(zero.displayedDistance,0);assert.ok(b>a)});
test('cheap stopping estimate stays within the visual truth tolerance',()=>{for(const traditional of [false,true])for(const speed of [80,300,700,1300]){const actual=simulateStoppingDistance(speed,{traditional}).distance,estimate=estimateStoppingDistance(speed,{traditional}),limit=Math.max(actual*.03,18);assert.ok(Math.abs(actual-estimate)<=limit,`${traditional}:${speed} ${estimate}/${actual}`)}});
test('difficulty and trace change assistance only',()=>{const table=plain(),physical=estimateStoppingDistance(900),hard=deriveAimPreview({table,cueBall:table.balls[0],shotDirection:{x:1,y:0},shotSpeed:900,assistance:.34,maxPhysicalTravel:physical}),trace=deriveAimPreview({table,cueBall:table.balls[0],shotDirection:{x:1,y:0},shotSpeed:900,assistance:.34,maxPhysicalTravel:physical,trace:true});assert.equal(hard.physicalReach,trace.physicalReach);assert.ok(trace.assistanceReach>hard.assistanceReach)});
