import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeTableFairness} from '../js/fairness.js';
import {dailySeed,generateCandidate,generateTable} from '../js/generator.js';
import {dailyChallengeConfig} from '../js/rules.js';
import {Physics,STEP} from '../js/physics.js';
import {calibrateShot} from '../js/physics-calibration.js';

const open=()=>({w:720,h:1120,bounds:{l:24,r:696,t:24,b:1096},balls:[{id:0,x:360,y:900,r:18,pocketed:false},{id:1,x:360,y:560,r:18,pocketed:false},{id:2,x:160,y:560,r:18,pocketed:false}],obstacles:[],rails:[],frictionZone:null,hole:{x:360,y:124,r:40},pockets:[],targetType:'portal',traditional:false});
function physicsOracle(table,witness,speed=calibrateShot(table).maxSpeed){const world=structuredClone(table);for(const ball of world.balls){ball.vx??=0;ball.vy??=0}if(world.hole)world.hole.disabled=true;const physics=new Physics(world);physics.shoot(witness.shotDirection.x*speed,witness.shotDirection.y*speed);while(physics.active)physics.step(STEP);return{firstCollision:physics.firstCollision,valid:physics.firstCollision===witness.objectId}}
function physicsFirstCollision(table,witness,speed){return physicsOracle(table,witness,speed).firstCollision}
function singleRoute(){const table=open();table.balls[2].pocketed=true;return table}
test('open portal fixture has a bounded feasible route',()=>{const result=analyzeTableFairness(open(),{difficulty:'relaxed'});assert.equal(result.accepted,true);assert.ok(result.metrics.openDirections>=6);assert.ok(result.metrics.targetRoutes>=1);assert.ok(result.witness.physicalReach>result.witness.cueDistance)});
test('cue trapped by bumpers is rejected with an explainable reason',()=>{const table=open(),cue=table.balls[0];table.obstacles=[{x:cue.x+55,y:cue.y,r:20},{x:cue.x-55,y:cue.y,r:20},{x:cue.x,y:cue.y+55,r:20},{x:cue.x,y:cue.y-55,r:20}];const result=analyzeTableFairness(table);assert.ok(result.reasons.includes('NO_CUE_EXIT'))});
test('blocked object-to-portal corridor is not accepted as a target route',()=>{const table=open();table.balls[2].pocketed=true;table.obstacles=[{x:360,y:320,r:36}];const result=analyzeTableFairness(table);assert.ok(result.reasons.includes('NO_TARGET_ROUTE'))});
test('candidate derivation and fair generation are deterministic',()=>{const input=[177,'normal',0,720,1120,{tableStyle:'echo',ballSet:'three'}],candidate=generateCandidate(...input);assert.deepEqual(candidate,generateCandidate(...input));assert.deepEqual(generateTable(...input),generateTable(...input))});
test('Daily uses canonical dimensions independently of viewport inputs',()=>{const config=dailyChallengeConfig(new Date('2026-09-11T18:00:00Z')),a=generateTable(config.seed,config.difficulty,config.adaptive,config.width,config.height,{tableStyle:config.tableStyle}),b=generateTable(config.seed,config.difficulty,config.adaptive,720,1120,{tableStyle:config.tableStyle});assert.deepEqual(a,b);assert.equal(config.seed,dailySeed(new Date('2026-09-11T01:00:00Z')))});
test('traditional layouts bypass fairness regeneration',()=>{const table=generateTable(83,'hard',0,720,1120,{tableStyle:'snooker',ballSet:'american',traditional:true});assert.equal(table.fairness,undefined);assert.equal(table.obstacles.length,0);assert.equal(table.frictionZone,null)});
test('inherited Echo Rails are analyzed and preserved',()=>{const rails=[{a:{x:60,y:80},b:{x:100,y:120},life:2}];const table=generateTable(91,'normal',0,720,1120,{tableStyle:'echo',ballSet:'three',initialRails:rails});assert.deepEqual(table.rails,rails);assert.notEqual(table.rails,rails)});
test('adaptive seed 1788459397 witness reaches its declared first object in Physics',()=>{const table=generateTable(1788459397,'adaptive',2,720,1120,{tableStyle:'echo',ballSet:'three'}),witness=table.fairness.witness;assert.ok(witness);assert.equal(witness.objectId,1);assert.equal(physicsFirstCollision(table,witness),witness.objectId)});
test('a cue on the target side of a portal object is not a valid ghost route',()=>{const table=open();table.balls[0].y=300;table.balls[2].pocketed=true;const result=analyzeTableFairness(table,{difficulty:'relaxed'});assert.equal(result.witness,null);assert.ok(result.reasons.includes('NO_TARGET_ROUTE'))});
test('ghost routing rejects blocked cue and object corridors and an out-of-bounds ghost',()=>{const cueBlocked=singleRoute();cueBlocked.obstacles=[{x:360,y:740,r:24}];assert.equal(analyzeTableFairness(cueBlocked,{difficulty:'relaxed'}).witness,null);const objectBlocked=singleRoute();objectBlocked.obstacles=[{x:360,y:330,r:24}];assert.equal(analyzeTableFairness(objectBlocked,{difficulty:'relaxed'}).witness,null);const outside=singleRoute();outside.balls[1].y=1070;assert.equal(analyzeTableFairness(outside,{difficulty:'relaxed'}).witness,null)});
test('Echo Rail segment clearance covers endpoints, midpoint, and parallel lanes',()=>{for(const rail of [{a:{x:360,y:750},b:{x:420,y:750}},{a:{x:300,y:750},b:{x:360,y:750}},{a:{x:330,y:750},b:{x:390,y:750}},{a:{x:382.9,y:650},b:{x:382.9,y:850}}]){const table=singleRoute();table.rails=[rail];assert.equal(analyzeTableFairness(table,{difficulty:'relaxed'}).witness,null)}const clear=singleRoute();clear.rails=[{a:{x:400,y:650},b:{x:400,y:850}}];assert.ok(analyzeTableFairness(clear,{difficulty:'relaxed'}).witness);});
test('Physics oracle rejects corrupted witness direction, object id, and speed',()=>{const table=singleRoute(),witness=analyzeTableFairness(table,{difficulty:'relaxed'}).witness,valid=physicsOracle(table,witness),wrongDirection=physicsOracle(table,{...witness,shotDirection:{x:1,y:0}}),wrongObject=physicsOracle(table,{...witness,objectId:2}),slow=physicsOracle(table,witness,1);assert.equal(valid.valid,true,JSON.stringify(valid));assert.equal(wrongDirection.valid,false,JSON.stringify(wrongDirection));assert.equal(wrongObject.valid,false,JSON.stringify(wrongObject));assert.equal(slow.valid,false,JSON.stringify(slow))});
