import {generateCandidate,generateTable} from '../js/generator.js';
import {analyzeTableFairness} from '../js/fairness.js';
const args=process.argv.slice(2),read=(name,fallback)=>{const i=args.indexOf(name);return i<0?fallback:Number(args[i+1])},seed=read('--seed',1337),cases=read('--cases',1000),raw=args.includes('--baseline');
const difficulties=['relaxed','normal','hard','adaptive'],summary=Object.fromEntries(difficulties.map(difficulty=>[difficulty,{cases:0,accepted:0,staticInvalid:0,feasibilityFailures:0,lowMargin:0,scores:[],reasons:{},attempts:[],fallbacks:0}]));let determinismFailures=0;
for(let index=0;index<cases;index++){
 const difficulty=difficulties[index%difficulties.length],adaptive=difficulty==='adaptive'?(index%4)-1:0,caseSeed=(seed+Math.imul(index+1,2654435761))>>>0,table=raw?generateCandidate(caseSeed,difficulty,adaptive,720,1120,{tableStyle:'echo',ballSet:'three'}):generateTable(caseSeed,difficulty,adaptive,720,1120,{tableStyle:'echo',ballSet:'three'}),analysis=raw?analyzeTableFairness(table,{difficulty,adaptive}):table.fairness,row=summary[difficulty];row.cases++;row.scores.push(analysis.difficultyScore);row.attempts.push(analysis.attempt||0);if(analysis.fallback)row.fallbacks++;if(analysis.accepted)row.accepted++;for(const reason of analysis.reasons){row.reasons[reason]=(row.reasons[reason]||0)+1;if(reason==='INVALID_STATIC_GEOMETRY')row.staticInvalid++;if(reason==='LOW_SOLUTION_MARGIN')row.lowMargin++;if(['NO_CUE_EXIT','NO_OBJECT_ACCESS','NO_TARGET_ROUTE'].includes(reason))row.feasibilityFailures++}
 const repeat=raw?analyzeTableFairness(structuredClone(table),{difficulty,adaptive}):generateTable(caseSeed,difficulty,adaptive,720,1120,{tableStyle:'echo',ballSet:'three'}).fairness;if(JSON.stringify(analysis)!==JSON.stringify(repeat))determinismFailures++;
}
const percentile=(values,p)=>values.length?values.slice().sort((a,b)=>a-b)[Math.min(values.length-1,Math.floor((values.length-1)*p))]:0;
const rows=difficulties.map(difficulty=>{const row=summary[difficulty];return{difficulty,cases:row.cases,accepted:row.accepted,acceptedPct:+(100*row.accepted/row.cases).toFixed(2),staticInvalid:row.staticInvalid,feasibilityFailures:row.feasibilityFailures,lowMargin:row.lowMargin,fallbacks:row.fallbacks,attemptMean:+(row.attempts.reduce((a,b)=>a+b,0)/row.attempts.length).toFixed(2),attemptP95:percentile(row.attempts,.95),scoreMean:+(row.scores.reduce((a,b)=>a+b,0)/row.scores.length).toFixed(3),scoreP95:+percentile(row.scores,.95).toFixed(3),reasons:JSON.stringify(row.reasons)}});console.table(rows);console.log(JSON.stringify({mode:raw?'baseline':'validation',cases,determinismFailures},null,2));if(!raw&&(determinismFailures||rows.some(row=>row.staticInvalid||row.feasibilityFailures)))process.exitCode=1;
