import {generateCandidate,generateTable} from '../js/generator.js';
import {analyzeTableFairness} from '../js/fairness.js';
import {Physics,STEP} from '../js/physics.js';
import {calibrateShot} from '../js/physics-calibration.js';

const args=process.argv.slice(2),read=(name,fallback)=>{const index=args.indexOf(name);return index<0?fallback:Number(args[index+1])},seed=read('--seed',1337),cases=read('--cases',1000),raw=args.includes('--baseline');
const difficulties=['relaxed','normal','hard','adaptive'],makeRow=()=>({cases:0,accepted:0,candidate0Accepted:0,retryCases:0,rejectedCandidates:0,staticInvalid:0,feasibilityFailures:0,lowMargin:0,scores:[],attempts:[],generationMs:[],reasons:{},fallbacks:0,degradedDifficulty:0,oracleCases:0,oracleFailures:0,determinismFailures:0}),summary=Object.fromEntries(difficulties.map(difficulty=>[difficulty,makeRow()]));
let determinismFailures=0,oracleCases=0,oracleFailures=0,firstCollisionMismatches=0,nonFinite=0;
for(let index=0;index<cases;index++){
 const difficulty=difficulties[index%difficulties.length],adaptive=difficulty==='adaptive'?(index%4)-1:0,caseSeed=(seed+Math.imul(index+1,2654435761))>>>0,started=performance.now(),table=raw?generateCandidate(caseSeed,difficulty,adaptive,720,1120,{tableStyle:'echo',ballSet:'three'}):generateTable(caseSeed,difficulty,adaptive,720,1120,{tableStyle:'echo',ballSet:'three'}),generationMs=performance.now()-started,analysis=raw?analyzeTableFairness(table,{difficulty,adaptive}):table.fairness,row=summary[difficulty];
 row.cases++;row.scores.push(analysis.difficultyScore);row.attempts.push(analysis.attempt||0);row.generationMs.push(generationMs);row.rejectedCandidates+=analysis.attempt||0;if(analysis.accepted)row.accepted++;if(analysis.accepted&&analysis.attempt===0)row.candidate0Accepted++;if((analysis.attempt||0)>0)row.retryCases++;if(analysis.fallback)row.fallbacks++;if(analysis.degradedDifficulty)row.degradedDifficulty++;
 for(const reason of analysis.reasons){row.reasons[reason]=(row.reasons[reason]||0)+1;if(reason==='INVALID_STATIC_GEOMETRY')row.staticInvalid++;if(reason==='LOW_SOLUTION_MARGIN')row.lowMargin++;if(['NO_CUE_EXIT','NO_OBJECT_ACCESS','NO_TARGET_ROUTE'].includes(reason))row.feasibilityFailures++}
 const repeat=raw?analyzeTableFairness(structuredClone(table),{difficulty,adaptive}):generateTable(caseSeed,difficulty,adaptive,720,1120,{tableStyle:'echo',ballSet:'three'}).fairness;if(JSON.stringify(analysis)!==JSON.stringify(repeat)){determinismFailures++;row.determinismFailures++}
 if(!raw&&analysis.physicallyFeasible&&analysis.witness){oracleCases++;row.oracleCases++;const world=structuredClone(table);if(world.hole)world.hole.disabled=true;const physics=new Physics(world),speed=calibrateShot(world).maxSpeed,witness=analysis.witness;physics.shoot(witness.shotDirection.x*speed,witness.shotDirection.y*speed);while(physics.active)physics.step(STEP);const finite=world.balls.every(ball=>Number.isFinite(ball.x)&&Number.isFinite(ball.y)&&Number.isFinite(ball.vx)&&Number.isFinite(ball.vy));if(!finite)nonFinite++;if(physics.firstCollision!==witness.objectId){oracleFailures++;row.oracleFailures++;firstCollisionMismatches++;if(oracleFailures<=3)console.log('oracle repro',JSON.stringify({caseSeed,difficulty,attempt:analysis.attempt,witness,actual:physics.firstCollision}))}}
}
const percentile=(values,p)=>values.length?values.slice().sort((a,b)=>a-b)[Math.min(values.length-1,Math.floor((values.length-1)*p))]:0;
const rows=difficulties.map(difficulty=>{const row=summary[difficulty];return{difficulty,cases:row.cases,candidate0Accepted:row.candidate0Accepted,retryCases:row.retryCases,rejectedCandidates:row.rejectedCandidates,accepted:row.accepted,fallbacks:row.fallbacks,degradedDifficulty:row.degradedDifficulty,attemptMean:+(row.attempts.reduce((a,b)=>a+b,0)/row.attempts.length).toFixed(2),attemptP95:percentile(row.attempts,.95),scoreMean:+(row.scores.reduce((a,b)=>a+b,0)/row.scores.length).toFixed(3),scoreP95:+percentile(row.scores,.95).toFixed(3),generationMeanMs:+(row.generationMs.reduce((a,b)=>a+b,0)/row.generationMs.length).toFixed(3),generationP95Ms:+percentile(row.generationMs,.95).toFixed(3),generationMaxMs:+Math.max(...row.generationMs).toFixed(3),oracleFailures:row.oracleFailures,determinismFailures:row.determinismFailures,reasons:JSON.stringify(row.reasons)}});console.table(rows);console.log(JSON.stringify({mode:raw?'baseline':'validation',cases,determinismFailures,oracleCases,oracleFailures,firstCollisionMismatches,nonFinite},null,2));if(!raw&&(determinismFailures||oracleFailures||nonFinite||rows.some(row=>row.staticInvalid||row.feasibilityFailures)))process.exitCode=1;
